const Discit = require('../classes/cls_discit');
const attacks = require('./attacks');

/* attacks:
    Thump, Pummel, First Strike, Tunnel, Hurl Attack, Barrage Of Fists, Coin Flip, Wobble, (normal)


    v in order of strength (low to high): 152436
    
    Mist Ray, Spray, Floodwater, Wave Shower, Pour Out, Infinity Rain, (water)

    Aflame, Torch, Magma Floor, Lava Shower, Spew, Burning Fury, (fire)

    Sprout, Snare, Vine Tangle, Thorn Shower, Leaf Blower, Ancient Force, (grass)

    Windmill, Flap, Tornado Assault, Vacuum Claw, Rip Up, Blink of an Eye, (flying)

    Smother, Cloud Over, Noxious Fumes, Toxin Shower, Slow Seep, Final Breath, (poison)

    Static, String Snare, Electron Pulse, Lightning Shower, Amper Craze, Dismissal, (electric)

    Uneasy, Stifle, Shadow Wrap, Pure Darkness, Silent Strangle, Heart Attack, (dark)

    Stare Down, Weaken, Strengthen, Toughen Up, Sprint, Quick Dodge, Sunrise, Beatdown, Max Buff, Max Nerf, (no dmg-normal)


    v no damage, only one effect (90% chance)

    Light, Spore Plant, Sleet, Bonk, Enchant, Charge Up, Suspicious Mixture
*/

const discits = {
    'Koulicious': new Discit('Water', [['Wave Shower', 39], ['Max Nerf', 45], ['Floodwater', 55], ['Infinity Rain', 64]], [], [78, 78, 98, 81, 115, 80], 'medium fast', [0, 3, 0, 0, 0, 0], 265, 45, 'The final stage of a Koul Discit. The bond that this creature shares with it\'s partner is said so be stronger than any other.'),
    'Koulade': new Discit('Water', [['Sleet', 18], ['Lightning Shower', 23], ['Sunrise', 30]], ['Koulicious', 35], [48, 72, 79, 80, 81, 60], 'fast', [1, 0, 0, 1, 0, 0], 147, 45, 'With a lot of time and care, Koulit has evolved into a stronger drink-Type Discit. And with enough training, the same thing could happen to Koulade...'),
    'Koulit': new Discit('Water', [['Thump', 1], ['Toughen Up', 1], ['Quick Dodge', 1], ['Mist Ray', 6], ['Pour Out', 10], ['Spray', 14]], ['Koulade', 16], [30, 60, 55, 65, 60, 40], 'fast', [0, 2, 0, 0, 0, 0], 62, 45, 'Don\'t be fooled by their icy glare! This chilly Discit it about as timid as they come.'),
    
    'Vastrunk': new Discit('grass', [['Thorn Shower', 39], ['Vine Tangle', 47], ['Max Buff', 55], ['Ancient Force', 64]], [], [130, 65, 90, 60, 85, 100], 'medium fast', [0, 0, 2, 1, 0, 0], 265, 45, 'If Branchid hits like a truck, then this thing hits like a tank. It\'s destructive force is such that small towns have been wiped out by just one Vastrunk.'),
    'Branchid': new Discit('grass', [['Flap', 18], ['Spore Plant', 23], ['Enchant', 30]], ['Vastrunk', 35], [75, 65, 70, 59, 70, 81], 'fast', [1, 0, 1, 0, 0, 0], 147, 45, 'Branchid hits like a truck, but that doesn\'t mean it can\'t take quite a few hits as well!'),
    'Leafid': new Discit('grass', [['Thump', 1], ['Strengthen', 1], ['Weaken', 1], ['Sprout', 6], ['Leaf Blower', 10], ['Snare', 14]], ['Branchid', 16], [55, 50, 50, 40, 55, 60], 'fast', [0, 0, 0, 0, 1, 1], 62, 45, 'Leafids are known to float around in the wind until they find the perfect trainer - sometimes it\'s hard to tell them apart from foliage.'),
    
    'Kelvynn': new Discit('fire', [['Lava Shower', 39], ['Magma Floor', 47], ['Burning Fury', 57], ['Beatdown', 64]], [], [103, 66, 104, 80, 109, 68], 'medium fast', [2, 0, 1, 0, 0, 0], 265, 45, 'Step within 100 feet of this Discit, and you can say goodbye to any liquid water you have on you. This Discit\'s immense heat is enough to melt strong metals, given the opportunity.'),
    'Selsiyus': new Discit('fire', [['Silent Strangle', 18], ['Light', 23], ['Pummel', 30]], ['Kelvynn', 35], [73, 60, 85, 60, 93, 49], 'fast', [0, 0, 1, 0, 0, 1], 147, 45, 'This fiery Discit is almost never found in the wild, but scientists are working to prevent their rapid extinction.'),
    'Ferenhyde': new Discit('fire', [['Thump', 1], ['Sprint', 1], ['Stare Down', 1], ['Aflame', 6], ['Spew', 10], ['Torch', 14]], ['Selsiyus', 16], [55, 40, 65, 50, 70, 30], 'fast', [0, 0, 2, 0, 0, 0], 62, 45, 'Yowch, this Discit is way too hot to touch! Luckily, it cools itself down near good trainers.'),
    
    'Kermutt': new Discit('normal', [['Thump', 1], ['Stare Down', 1], ['Tunnel', 4], ['Coin Flip', 12], ['Pummel', 18], ['Light', 24], ['Sprint', 27], ['Sunrise', 31], ['Hurl Attack', 36], ['Tornado Assault', 40]], [], [75, 65, 80, 68, 61, 71], 'fast', [1, 0, 0, 0, 1, 0], 147, 255, 'Kermutts often hunt in packs, and they use their impressive sense of smell to locate hostile Discits.'),
    'Tailick': new Discit('normal', [['Thump', 1], ['Stare Down', 1], ['Tunnel', 4], ['Coin Flip', 12], ['Pummel', 18]], ['Kermutt', 22], [50, 43, 45, 38, 50, 29], 'fast', [1, 0, 0, 0, 0, 0], 51, 255, 'Tailick\'s bark is much worse than his bite... but don\'t worry, neither of them are very powerful.'),
    
    'Bluricane': new Discit('flying', [['Thump', 1], ['Windmill', 5], ['Pour Out', 12], ['Rip Up', 16], ['Quick Dodge', 20], ['Sleet', 27], ['Vacuum Claw', 31], ['Flap', 36], ['Spore Plant', 41], ['Sunrise', 47], ['Tornado Assault', 56], ['Blink of an Eye', 62]], [], [75, 115, 78, 100, 70, 95], 'medium fast', [3, 0, 0, 0, 0, 0], 280, 125, 'It is said that Bluricanes once inhabited the Earth in swarms, but most of them are in zoos by now. This means that you they\'re very hard to find in the grass.'),
    'Tornatian': new Discit('flying', [['Thump', 1], ['Windmill', 5], ['Pour Out', 12], ['Rip Up', 16], ['Quick Dodge', 20], ['Sleet', 27], ['Vacuum Claw', 31], ['Flap', 36]], ['Bluricane', 40], [68, 90, 68, 90, 35, 72], 'medium fast', [0, 2, 0, 1, 0, 0], 160, 235, 'With a Flap of its feathers, Tornatian can stir up a breeze and catch other Discits off guard. This also helps it stay in the air for long periods of time!'),
    'Stormish': new Discit('flying', [['Thump', 1], ['Windmill', 5], ['Pour Out', 12], ['Rip Up', 16], ['Quick Dodge', 20]], ['Tornatian', 25], [40, 100, 10, 10, 40, 55], 'medium fast', [0, 2, 0, 0, 0, 0], 62, 240, 'Stormish almost resembles a seagull - the only real difference is that seagulls can\'t put up a fight.'),
    
    'Whiskitch': new Discit('normal', [['Wobble', 1], ['Sprint', 1], ['Thump', 3], ['First Strike', 7], ['Uneasy', 11], ['Bonk', 14], ['Stare Down', 19], ['Tunnel', 22], ['Pummel', 26], ['String Snare', 30], ['Suspicious Mixture', 35], ['Heart Attack', 61]], [], [82, 83, 60, 48, 90, 58], 'fast', [2, 0, 0, 0, 1, 0], 150, 255, 'A speedy and well-balanced Discit, Whiskitch is a tough opponent. Don\'t let it get any sand in your eyes with that Whirlwind attack!'),
    'Furrow': new Discit('normal', [['Wobble', 1], ['Sprint', 1], ['Thump', 3], ['First Strike', 7], ['Uneasy', 11], ['Bonk', 14]], ['Whiskitch', 15], [66, 66, 40, 38, 90, 25], 'fast', [0, 1, 0, 1, 0, 0], 55, 255, 'Every day is Groundhog Day for Furrows. At least, that\'s what they think - Furrows are known for stealing bread and small items.'),
    
    'Yavolt': new Discit('electric', [['Thump', 1], ['Weaken', 1], ['Static', 6], ['Amper Craze', 10], ['String Snare', 14], ['Charge Up', 18], ['Sunrise', 24], ['Toxin Shower', 30], ['Lightning Shower', 39], ['Beatdown', 48], ['Electron Pulse', 56], ['Dismissal', 64]], [], [80, 40, 85, 90, 65, 75], 'medium fast', [2, 0, 0, 0, 0, 0], 160, 190, 'Yavolts are often hired as electricians, because they have great control over the electric aura coming off of them.'),
    'Amperas': new Discit('electric', [['Thump', 1], ['Weaken', 1], ['Static', 6], ['Amper Craze', 10], ['String Snare', 14], ['Charge Up', 18]], ['Yavolt', 21], [64, 24, 82, 75, 42, 70], 'medium fast', [0, 1, 1, 0, 0, 0], 116, 220, 'Amperas is a well-tempered creature on land, but don\'t ever let it near water. That thing will let off a charge powerful enough to tranquilize an adult Wavelash.'),
    
    'Fumulus': new Discit('poison', [['Thump', 1], ['Wobble', 1], ['Suspicious Mixture', 1], ['Smother', 10], ['Slow Seep', 14], ['Cloud Over', 18], ['Weaken', 24], ['Strengthen', 30], ['Toxin Shower', 39], ['Enchant', 48], ['Noxious Fumes', 56], ['Final Breath', 66]], [], [95, 88, 88, 97, 20, 110], 'medium slow', [1, 0, 0, 1, 0, 0], 243, 70, 'Fumulus is a shadowy Discit that resembles a small cloud. Be sure not to walk inside its radius, though - the poison is quite strong.'),
    'Gasper': new Discit('poison', [['Thump', 1], ['Wobble', 1], ['Suspicious Mixture', 1], ['Smother', 10], ['Slow Seep', 14], ['Cloud Over', 18], ['Weaken', 24], ['Strengthen', 30]], ['Fumulus', 36], [75, 74, 77, 77, 10, 95], 'medium slow', [0, 0, 0, 0, 1, 1], 141, 200, 'Some say that Gaspers are born with breathing issues, others say that they just like sounding annoying. Either way, it\'s not pleasant to be around \'em.'),
    
    'Flurrious': new Discit('flying', [['Thump', 1], ['Toughen Up', 1], ['First Strike', 4], ['Windmill', 8], ['Rip Up', 12], ['Sleet', 18], ['Spray', 24], ['Sunrise', 30], ['Vacuum Claw', 39], ['Flap', 44], ['Hurl Attack', 49], ['Tornado Assault', 55]], [], [120, 50, 50, 10, 120, 80], 'medium slow', [3, 0, 0, 0, 0, 0], 148, 173, 'While Flurrious is not known to evolve, it can still fend for itself if the need be. Generally, these birds fly in a V shape to conserve energy and protect themselves.'),
    
    'Godzimian': new Discit('fire', [['Wobble', 1], ['Sprint', 1], ['Thump', 7], ['Aflame', 12], ['Spew', 16], ['Charge Up', 20], ['Torch', 24], ['Light', 30], ['Quick Dodge', 37], ['Lightning Shower', 42], ['Coin Flip', 46], ['Lava Shower', 52], ['Magma Floor', 57]], [], [200, 45, 18, 19, 200, 69], 'fast', [3, 0, 0, 0, 0, 0], 295, 30, 'Godzimian is the monstrous flip-side of Slimshaidy, and saying that it spits fire would be an understatement. The offensive power of this Discit is known worldwide, but not so much its health.'),
    'Slimshaidy': new Discit('fire', [['Wobble', 1], ['Sprint', 1], ['Thump', 7], ['Aflame', 12], ['Spew', 16], ['Charge Up', 20], ['Torch', 24], ['Light', 30], ['Quick Dodge', 37]], [], ['Godzimian', 41], [200, 7, 15, 14, 200, 5], 'fast', [1, 0, 0, 0, 1, 0], 175, 110, 'This Discit spits fire, on and off the battlefield. You should hear the collabs it does with many of the human trainers.'),
    
    'Wavelash': new Discit('Water', [['Thump', 1], ['Toughen Up', 1], ['Mist Ray', 5], ['First Strike', 9], ['Pour Out', 12], ['Weaken', 17], ['Snare', 21], ['Bonk', 25], ['Spray', 27], ['Wave Shower', 32], ['Hurl Attack', 38], ['Sleet', 41], ['Floodwater', 48], ['Max Buff', 53], ['Infinity Rain', 62]], [], [94, 80, 86, 110, 65, 90], 'fast', [0, 0, 0, 3, 0, 0], 263, 138, 'This Discit is nothing short of mythical. Few can say that they have seen a Wavelash, and those who do barely make it out alive.'),
    'Reflexic': new Discit('Water', [['Thump', 1], ['Toughen Up', 1], ['Mist Ray', 5], ['First Strike', 9], ['Pour Out', 12], ['Weaken', 17], ['Snare', 21], ['Bonk', 25], ['Spray', 27], ['Wave Shower', 32]], ['Wavelash', 37], [80, 75, 90, 110, 60, 52], 'medium fast', [0, 0, 1, 1, 0, 0], 181, 167, 'While it does live in the water, this Discit looks nothing like a fish. It has four limbs, two of which are used for quick paddling.'),
    'Aquish': new Discit('Water', [['Thump', 1], ['Toughen Up', 1], ['Mist Ray', 5], ['First Strike', 9], ['Pour Out', 12]], ['Reflexic', 14], [55, 65, 68, 90, 45, 50], 'medium fast', [0, 2, 0, 0, 0, 0], 109, 226, 'A shy Discit that usually resides in small ponds. If you\'re lucky, you might catch one during jumping season!'),
    
    'Tearose': new Discit('grass', [['Thump', 1], ['Spore Plant', 1], ['Sprout', 5], ['Suspicious Mixture', 10], ['Leaf Blower', 14], ['Cloud Over', 18], ['Tunnel', 23], ['Stifle', 29], ['Snare', 33], ['Enchant', 40], ['Thorn Shower', 45], ['Vine Tangle', 48], ['Beatdown', 54], ['Shadow Wrap', 58], ['Max Nerf', 59]], [], [60, 45, 10, 12, 5, 380], 'medium slow', [0, 1, 1, 1, 1, 0], 270, 149, 'Don\'t be fooled by the nice name - it starts with \'tear\' for a reason. These Discits are known to rip their enemies apart with thorns and then consume them to add to their massive stature.'),
    'Wrathorn': new Discit('grass', [['Thump', 1], ['Spore Plant', 1], ['Sprout', 5], ['Suspicious Mixture', 10], ['Leaf Blower', 14], ['Cloud Over', 18], ['Tunnel', 23], ['Stifle', 29], ['Snare', 33]], ['Tearose', 36], [40, 40, 10, 11, 5, 330], 'medium slow', [0, 1, 0, 0, 0, 1], 154, 169, 'If you thought Ripetal could take a lot of hits, Wrathorn is not the opponent for you. Luckily, catching them isn\'t too much of a challenge.'),
    'Ripetal': new Discit('grass', [['Thump', 1], ['Spore Plant', 1], ['Sprout', 5], ['Suspicious Mixture', 10], ['Leaf Blower', 14], ['Cloud Over', 18], ['Tunnel', 23]], ['Wrathorn', 25], [20, 35, 0, 0, 5, 250], 'medium slow', [0, 1, 0, 0, 0, 0], 68, 187, 'Ripetal is able to hide from predators by disguising itself as a rose. It can\'t throw a punch to save its life, but that massive health bar ensures that most Ripetals live for quite a while.'),
    
    'Tuburn': new Discit('fire', [['Thump', 1], ['Light', 1], ['Quick Dodge', 1], ['Aflame', 6], ['Static', 10], ['Spew', 14], ['Strengthen', 17], ['Torch', 25], ['Enchant', 29], ['Flap', 34], ['Lava Shower', 38], ['Coin Flip', 42], ['Bonk', 48], ['Magma Floor', 54], ['Dismissal', 60]], [], [81, 66, 97, 48, 78, 80], 'medium fast', [1, 0, 2, 0, 0, 0], 200, 108, 'Tuburn probably got its name from the two different temperatures that it exerts. Contrary to popular opinion, Tuburn actually has no control over this.'),
    'Flamesprit': new Discit('fire', [['Thump', 1], ['Light', 1], ['Quick Dodge', 1], ['Aflame', 6], ['Static', 10], ['Spew', 14], ['Strengthen', 17]], ['Tuburn', 23], [64, 50, 78, 47, 63, 70], 'fast', [2, 0, 0, 0, 0, 0], 118, 209, 'Many believe Flamesprit to be only a myth, which is probably because of their ability to self-extinguish. If you found one of these, it says a lot about your skill as a trainer.'),
    'Searish': new Discit('fire', [['Thump', 1], ['Light', 1], ['Quick Dodge', 1], ['Aflame', 6]], ['Flamesprit', 9], [51, 46, 62, 46, 52, 60], 'slow', [0, 0, 1, 0, 0, 0], 65, 255, 'A speedy fire sprite that plays a part in many fairy tales. It is said that Searishes only come out right after sunset.'),
    
    'Flubunny': new Discit('normal', [['Wobble', 1], ['Thump', 1], ['First Strike', 5], ['Uneasy', 9], ['Quick Dodge', 14], ['Leaf Blower', 17], ['Bonk', 22], ['Tunnel', 25], ['Pummel', 30], ['Coin Flip', 33], ['String Snare', 36], ['Hurl Attack', 42]], [], [51, 49, 55, 45, 95, 50], 'medium fast', [0, 0, 1, 0, 0, 0], 78, 213, 'One of the Discits most closely related to animals, this bunny is friendly to many. Unfortunately, the average life expectancy for these is quite short, and they are never given a chance to evolve.'),
    
    'Cloakork': new Discit('dark', [['Thump', 1], ['Uneasy', 6], ['Sprint', 10], ['Silent Strangle', 14], ['Charge Up', 18], ['Weaken', 21], ['Stifle', 25], ['Pummel', 29], ['Sunrise', 34], ['Enchant', 38], ['Pure Darkness', 42], ['Sleet', 47], ['Shadow Wrap', 54], ['Max Buff', 59], ['Max Nerf', 61], ['Heart Attack', 66]], [], [85, 110, 90, 90, 74, 90], 'medium slow', [0, 3, 0, 0, 0, 1], 278, 24, 'Cloakork is very hard to catch in the wild, and even harder to evolve from Shadisk. It is, however, very common to find, so many trainers are still working on catching one.'),
    'Shadisk': new Discit('dark', [['Thump', 1], ['Uneasy', 6], ['Sprint', 10], ['Silent Strangle', 14], ['Charge Up', 18], ['Weaken', 21], ['Stifle', 25], ['Pummel', 29], ['Sunrise', 34], ['Enchant', 38], ['Pure Darkness', 42], ['Sleet', 47]], ['Cloakork', 51], [65, 90, 85, 83, 73, 77], 'slow', [0, 1, 1, 0, 0, 0], 223, 32, 'One of the few shapeshifting Discits out there, Shadisk is a huge pain to catch. But the payoff is pretty large once you train it for a while.'),
    
    'Raskett': new Discit('dark', [['Wobble', 1], ['Thump', 1], ['First Strike', 5], ['Uneasy', 11], ['Strengthen', 16], ['Quick Dodge', 20], ['Silent Strangle', 24], ['Stifle', 27], ['Sleet', 31], ['Pure Darkness', 38], ['Wave Shower', 38], ['Lava Shower', 38], ['Thorn Shower', 38], ['Vacuum Claw', 38], ['Toxin Shower', 38], ['Lightning Shower', 38], ['Hurl Attack', 43], ['Bonk', 46], ['Shadow Wrap', 51], ['Beatdown', 54], ['Heart Attack', 57], ['Final Breath', 61]], [], [90, 85, 95, 90, 75, 95], 'fast', [0, 2, 0, 0, 0, 0], 265, 64, 'Going from Wasket all the way to Raskett is hard work, but it pays off. This all-around Discit is good in many situations, and it\'s also fairly hard to catch without having evolved earlier.'),
    'Tasket': new Discit('dark', [['Wobble', 1], ['Thump', 1], ['First Strike', 5], ['Uneasy', 11], ['Strengthen', 16], ['Quick Dodge', 20], ['Silent Strangle', 24], ['Stifle', 27], ['Sleet', 31]], ['Raskett', 33], [75, 65, 72, 67, 60, 81], 'fast', [2, 0, 0, 0, 0, 0], 146, 187, 'Tasket usually strikes from the shadows, which works well considering that it\'s made of ink. This Discit is the reason why many in the area don\'t go out at night.'),
    'Mascit': new Discit('dark', [['Wobble', 1], ['Thump', 1], ['First Strike', 5], ['Uneasy', 11], ['Strengthen', 16], ['Quick Dodge', 20]], ['Tasket', 23], [54, 45, 51, 51, 43, 56], 'fast', [0, 1, 0, 1, 0, 0], 59, 247, 'A mediocre upgrade from Wasket and Baskett, this Discit is decent all around. It\'s hard to tell apart from Baskett, as they are both pitch black in ink.'),
    'Baskett': new Discit('dark', [['Wobble', 1], ['Thump', 1], ['First Strike', 5], ['Uneasy', 11]], ['Mascit', 15], [43, 37, 41, 35, 45, 48], 'fast', [0, 0, 0, 0, 1, 0], 58, 255, 'Baskett is a small, humanoid creature that is made completely out of ink. Nobody has figured out exactly how it stays together.'),
    'Wasket': new Discit('dark', [['Wobble', 1], ['Thump', 1], ['First Strike', 5]], ['Baskett', 8], [23, 24, 28, 30, 25, 32], 'fast', [0, 0, 0, 0, 0, 1], 23, 255, 'Probably the weakest Discit out there, Wasket is better at running away than anything else. But who knows, it might get much stronger over time...'),
    
    'Gikatail': new Discit('normal', [['Thump', 1], ['Stare Down', 1], ['Static', 6], ['Leaf Blower', 10], ['Bonk', 15], ['Pummel', 19], ['Coin Flip', 23], ['String Snare', 28], ['Lightning Shower', 32], ['Thorn Shower', 34], ['Charge Up', 38], ['Vine Tangle', 45], ['Hurl Attack', 49], ['Sprint', 51], ['Max Buff', 55], ['Dismissal', 60]], [], [90, 84, 89, 89, 93, 92], 'medium fast', [0, 0, 0, 0, 0, 3], 268, 4, 'Most of Gikatail\'s attack strength comes from its massive tail - it also uses it as a moving blanket when it\'s especially cold outside.'),
    'Simmatree': new Discit('normal', [['Thump', 1], ['Stare Down', 1], ['Static', 6], ['Leaf Blower', 10], ['Bonk', 15], ['Pummel', 19], ['Coin Flip', 23], ['String Snare', 28], ['Lightning Shower', 32], ['Thorn Shower', 34], ['Charge Up', 38]], ['Gikatail', 42], [77, 68, 78, 79, 64, 64], 'medium fast', [1, 1, 0, 0, 0, 0], 152, 57, 'Just like their previous stage, Simmatrees have a tendency to split apart. In fact, their name might have something to do with it.'),
    'Weizel': new Discit('normal', [['Thump', 1], ['Stare Down', 1], ['Static', 6], ['Leaf Blower', 10], ['Bonk', 15], ['Pummel', 19], ['Coin Flip', 23]], ['Simmatree', 27], [64, 67, 76, 70, 52, 59], 'medium fast', [0, 0, 1, 1, 0, 0], 106, 72, 'Weizels are known to cleave themselves into two smaller Weizels in order to hide from enemies. Then afterwards, they join together again!'),
    
    'Sirilik III': new Discit('poison', [['Thump', 1], ['Weaken', 1], ['Slow Seep', 5], ['Amper Craze', 10], ['Sprint', 14], ['Suspicious Mixture', 17], ['Charge Up', 20], ['Smother', 23], ['Cloud Over', 27], ['Spore Plant', 30], ['Light', 34], ['Lightning Shower', 39], ['Toxin Shower', 42], ['Sunrise', 45], ['Electron Pulse', 53]], [], [85, 85, 85, 85, 85, 85], 'medium fast', [3, 0, 0, 0, 0, 0], 248, 50, 'So far, Sirilik III is the most advanced robot out there! They are so similar to Discits that many have made close friends in the wild.'),
    'Sirilik II': new Discit('poison', [['Thump', 1], ['Weaken', 1], ['Slow Seep', 5], ['Amper Craze', 10], ['Sprint', 14], ['Suspicious Mixture', 17], ['Charge Up', 20], ['Smother', 23], ['Cloud Over', 27], ['Spore Plant', 30], ['Light', 34], ['Lightning Shower', 39], ['Toxin Shower', 42], ['Sunrise', 45]], ['Sirilik III', 48], [75, 75, 75, 75, 75, 75], 'medium fast', [2, 0, 0, 0, 0, 0], 162, 150, 'Siriliks were made to host linear upgrades as they learned more about their powers. The best place to learn about these is probably *The Factory*.'),
    'Sirilik I': new Discit('poison', [['Thump', 1], ['Weaken', 1], ['Slow Seep', 5], ['Amper Craze', 10], ['Sprint', 14], ['Suspicious Mixture', 17], ['Charge Up', 20]], ['Sirilik II', 24], [65, 65, 65, 65, 65, 65], 'medium fast', [1, 0, 0, 0, 0, 0], 124, 250, 'Zzt zzt - - Sirilik online! *\'Your wish is my command.\'*'),
    
    'Zappstrike': new Discit('electric', [['Thump', 1], ['Quick Dodge', 1], ['Static', 4], ['First Strike', 8], ['Amper Craze', 12], ['Toughen Up', 16], ['String Snare', 20], ['Charge Up', 28], ['Flap', 32], ['Lightning Shower', 36], ['Sunrise', 40], ['Electron Pulse', 44]], [], [60, 55, 70, 68, 90, 60], 'medium fast', [1, 1, 0, 0, 0, 0], 143, 90, 'Unlike its smaller counterpart, Zappstrike is a little more difficult to handle. As long as you don\'t touch its beak, you should be fine.'),
    'Shocklet': new Discit('electric', [['Thump', 1], ['Quick Dodge', 1], ['Static', 4], ['First Strike', 8], ['Amper Craze', 12], ['Toughen Up', 16], ['String Snare', 20]], ['Zappstrike', 24], [40, 35, 50, 54, 80, 40], 'medium fast', [1, 0, 0, 0, 0, 0], 56, 245, 'This small yellow bird is actually completely harmless! Set up a birdfeeder, you may find one approaching.'),
    
    'Rivolley': new Discit('fire', [['Thump', 1], ['Strengthen', 1], ['Aflame', 4], ['First Strike', 8], ['Spew', 12], ['Sprint', 16], ['Torch', 20], ['Light', 28], ['Cloud Over', 32], ['Lava Shower', 36], ['Max Buff', 40], ['Magma Floor', 44]], [], [90, 60, 68, 55, 70, 60], 'medium fast', [0, 0, 1, 0, 1, 0], 141, 92, 'Rivolleys are about ten times larger than Sunlets, so breeders have learned to predict when the transformation starts. Rivolleys are also more quick to anger, but they sure are beautiful.'),
    'Sunlet': new Discit('fire', [['Thump', 1], ['Strengthen', 1], ['Aflame', 4], ['First Strike', 8], ['Spew', 12], ['Sprint', 16], ['Torch', 20]], ['Rivolley', 24], [80, 40, 54, 35, 50, 40], 'medium fast', [0, 0, 0, 0, 1, 0], 58, 241, 'This tiny red parakeet is usually kept as a pet, but they are also able to survive in the wild due to their ability to make quick decisions.'),
    
    'Simorchid': new Discit('grass', [['Thump', 1], ['Toughen Up', 1], ['Sprout', 4], ['First Strike', 8], ['Leaf Blower', 12], ['Tunnel', 16], ['Snare', 20], ['Spore Plant', 28], ['Stifle', 32], ['Thorn Shower', 36], ['Hurl Attack', 40], ['Vine Tangle', 44]], [], [70, 68, 55, 60, 60, 90], 'medium fast', [0, 1, 0, 1, 0, 0], 142, 82, 'These fun-loving birds can often be found splashing around in natural pools. It\'s said that they have developed a very complex language due to their great social skills.'),
    'Sproutlet': new Discit('grass', [['Thump', 1], ['Toughen Up', 1], ['Sprout', 4], ['First Strike', 8], ['Leaf Blower', 12], ['Tunnel', 16], ['Snare', 20]], ['Simorchid', 24], [50, 54, 35, 40, 40, 80], 'medium fast', [0, 0, 0, 1, 0, 0], 54, 241, 'While Sproutlets are naturally green, these bird-like Discits are known for being able to change color in order to camouflage. They are probably born green because of where they tend to live - the jungle.'),
    
    'Streamur': new Discit('Water', [['Thump', 1], ['Weaken', 1], ['Mist Ray', 4], ['First Strike', 8], ['Pour Out', 12], ['Stare Down', 16], ['Spray', 20], ['Sleet', 28], ['Coin Flip', 32], ['Wave Shower', 36], ['Max Nerf', 40], ['Floodwater', 44]], [], [68, 90, 60, 60, 55, 70], 'medium fast', [0, 2, 0, 0, 0, 0], 140, 90, 'As the name suggests, Streamurs tend to live near waterfalls or small streams. They can store a large amount of water in their beaks, which is great for self-defense.'),
    'Droppelet': new Discit('Water', [['Thump', 1], ['Weaken', 1], ['Mist Ray', 4], ['First Strike', 8], ['Pour Out', 12], ['Stare Down', 16], ['Spray', 20]], ['Streamur', 24], [54, 80, 40, 40, 35, 50], 'medium fast', [0, 1, 0, 0, 0, 0], 60, 255, 'The wings of a Droppelet can adapt to water quickly, such that they are fast traveling through any medium.'),
    
    'Slithan': new Discit('poison', [['Thump', 1], ['Static', 6], ['Suspicious Mixture', 10], ['Slow Seep', 14], ['Amper Craze', 16], ['Toughen Up', 20], ['String Snare', 24], ['Charge Up', 30], ['Toxin Shower', 35], ['Noxious Fumes', 40]], [], [78, 71, 46, 90, 135, 77], 'fast', [0, 0, 0, 0, 2, 0], 232, 71, 'Unlike most Discit evolutions, Slithan is actually very different from Tulong (well, I guess they are both snakes). They differ greatly in size and type, and Slithan is poisonous while Tulong is electric.'),
    'Tulong': new Discit('electric', [['Thump', 1], ['Static', 6], ['Suspicious Mixture', 10], ['Slow Seep', 14], ['Amper Craze', 16], ['Toughen Up', 20], ['String Snare', 24]], ['Slithan', 27], [65, 63, 42, 78, 120, 69], 'slow', [0, 0, 0, 0, 2, 0], 157, 113, 'A snake-like Discit, Tulongs have the biggest advantage in their incredible speed. Instead of being poisonous like one might think, Tulongs actually give off a small electric charge.'),
    
    'Legenden': new Discit('flying', [['Thump', 1], ['Quick Dodge', 1], ['Windmill', 5], ['First Strike', 10], ['Rip Up', 14], ['Spew', 17], ['Light', 22], ['Flap', 26], ['Bonk', 29], ['Torch', 34], ['Sprint', 39], ['Vacuum Claw', 43], ['Hurl Attack', 47], ['Beatdown', 53], ['Magma Floor', 57], ['Barrage Of Fists', 61], ['Blink of an Eye', 66]], [], [90, 74, 99, 98, 76, 88], 'medium slow', [0, 0, 1, 1, 0, 0], 260, 16, 'Legendens are incredibly hard to catch, mostly because of how high they can fly. Once you do manage to get near one, they\'ll usually notice and make a speedy getaway.'),
    'Talemes': new Discit('flying', [['Thump', 1], ['Quick Dodge', 1], ['Windmill', 5], ['First Strike', 10], ['Rip Up', 14], ['Spew', 17], ['Light', 22], ['Flap', 26], ['Bonk', 29], ['Torch', 34], ['Sprint', 39], ['Vacuum Claw', 43], ['Hurl Attack', 47]], ['Legenden', 52], [79, 60, 80, 78, 50, 72], 'medium slow', [0, 0, 1, 1, 0, 0], 146, 37, 'Talemes are the subject of many a fairy tale, because they look almost like part of a fantasy. The way that Light bounces off their scales is very captivating.'),
    'Miracule': new Discit('flying', [['Thump', 1], ['Quick Dodge', 1], ['Windmill', 5], ['First Strike', 10], ['Rip Up', 14], ['Spew', 17], ['Light', 22], ['Flap', 26], ['Bonk', 29]], ['Talemes', 31], [47, 52, 65, 62, 36, 49], 'medium slow', [0, 0, 0, 1, 0, 0], 63, 42, 'Miracules lay their eggs in the water, and then the babies are taught to use their wings to get to the surface. In some ways, it\'s more risk-free than what birds usually do.'),
    
    'Stilagon': new Discit('dark', [['Pummel', 1], ['Hurl Attack', 40], ['Pure Darkness', 44], ['Vacuum Claw', 48], ['Sleet', 53], ['Shadow Wrap', 57], ['Sunrise', 63], ['Ancient Force', 63], ['Heart Attack', 68]], [], [91, 86, 95, 92, 100, 99], 'medium slow', [2, 0, 0, 0, 1, 0], 292, 63, 'These proud dragons are feared by all. They tend to stay in small packs and inhabit mountains that are far away from anything urban.'),
    
    'Prizeri': new Discit('normal', [['Thump', 1], ['Tunnel', 70], ['Light', 70], ['Magma Floor', 70], ['Hurl Attack', 72], ['Max Buff', 75], ['Max Nerf', 75], ['Final Breath', 77], ['Charge Up', 78], ['Barrage Of Fists', 83]], [], [110, 100, 110, 100, 100, 100], 'medium fast', [1, 1, 1, 1, 1, 1], 335, 12, 'The rarest Discit of all time, given only to the illustrious champions of Dieze. Be careful with this one, because there\'s only a single opportunity to catch it per trainer.')
    //water, fire, grass, poison, flying, electric     
};

module.exports = discits;

